// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Carts.proto

package com.eric.spring.boot.collections.protoc_generated;

public final class CartsProtoImpl {
  private CartsProtoImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Carts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Carts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Carts.proto\032\016CartItem.proto\"1\n\005Carts\022\n" +
      "\n\002id\030\001 \001(\t\022\034\n\tcartItems\030\002 \003(\0132\t.CartItem" +
      "BE\n1com.eric.spring.boot.collections.pro" +
      "toc_generatedB\016CartsProtoImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.eric.spring.boot.collections.protoc_generated.CartItemImpl.getDescriptor(),
        });
    internal_static_Carts_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Carts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Carts_descriptor,
        new java.lang.String[] { "Id", "CartItems", });
    com.eric.spring.boot.collections.protoc_generated.CartItemImpl.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
