// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Carts.proto

package com.eric.spring.boot.collections.protoc_generated;

public interface CartsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Carts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  java.util.List<com.eric.spring.boot.collections.protoc_generated.CartItem> 
      getCartItemsList();
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  com.eric.spring.boot.collections.protoc_generated.CartItem getCartItems(int index);
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  int getCartItemsCount();
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  java.util.List<? extends com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder> 
      getCartItemsOrBuilderList();
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder getCartItemsOrBuilder(
      int index);
}
