// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartItem.proto

package com.eric.spring.boot.collections.protoc_generated;

public interface CartItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CartItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int32 quantity = 21;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>repeated .Items item = 3;</code>
   */
  java.util.List<com.eric.spring.boot.collections.protoc_generated.Items> 
      getItemList();
  /**
   * <code>repeated .Items item = 3;</code>
   */
  com.eric.spring.boot.collections.protoc_generated.Items getItem(int index);
  /**
   * <code>repeated .Items item = 3;</code>
   */
  int getItemCount();
  /**
   * <code>repeated .Items item = 3;</code>
   */
  java.util.List<? extends com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder> 
      getItemOrBuilderList();
  /**
   * <code>repeated .Items item = 3;</code>
   */
  com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder getItemOrBuilder(
      int index);
}
