// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CartItem.proto

package com.eric.spring.boot.collections.protoc_generated;

/**
 * Protobuf type {@code CartItem}
 */
public final class CartItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CartItem)
    CartItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CartItem.newBuilder() to construct.
  private CartItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CartItem() {
    id_ = "";
    item_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CartItem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CartItem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              item_ = new java.util.ArrayList<com.eric.spring.boot.collections.protoc_generated.Items>();
              mutable_bitField0_ |= 0x00000001;
            }
            item_.add(
                input.readMessage(com.eric.spring.boot.collections.protoc_generated.Items.parser(), extensionRegistry));
            break;
          }
          case 168: {

            quantity_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        item_ = java.util.Collections.unmodifiableList(item_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.eric.spring.boot.collections.protoc_generated.CartItemImpl.internal_static_CartItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.eric.spring.boot.collections.protoc_generated.CartItemImpl.internal_static_CartItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.eric.spring.boot.collections.protoc_generated.CartItem.class, com.eric.spring.boot.collections.protoc_generated.CartItem.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 21;
  private int quantity_;
  /**
   * <code>int32 quantity = 21;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int ITEM_FIELD_NUMBER = 3;
  private java.util.List<com.eric.spring.boot.collections.protoc_generated.Items> item_;
  /**
   * <code>repeated .Items item = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.eric.spring.boot.collections.protoc_generated.Items> getItemList() {
    return item_;
  }
  /**
   * <code>repeated .Items item = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder> 
      getItemOrBuilderList() {
    return item_;
  }
  /**
   * <code>repeated .Items item = 3;</code>
   */
  @java.lang.Override
  public int getItemCount() {
    return item_.size();
  }
  /**
   * <code>repeated .Items item = 3;</code>
   */
  @java.lang.Override
  public com.eric.spring.boot.collections.protoc_generated.Items getItem(int index) {
    return item_.get(index);
  }
  /**
   * <code>repeated .Items item = 3;</code>
   */
  @java.lang.Override
  public com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder getItemOrBuilder(
      int index) {
    return item_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < item_.size(); i++) {
      output.writeMessage(3, item_.get(i));
    }
    if (quantity_ != 0) {
      output.writeInt32(21, quantity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (int i = 0; i < item_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, item_.get(i));
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(21, quantity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.eric.spring.boot.collections.protoc_generated.CartItem)) {
      return super.equals(obj);
    }
    com.eric.spring.boot.collections.protoc_generated.CartItem other = (com.eric.spring.boot.collections.protoc_generated.CartItem) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (!getItemList()
        .equals(other.getItemList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    if (getItemCount() > 0) {
      hash = (37 * hash) + ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getItemList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.eric.spring.boot.collections.protoc_generated.CartItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.eric.spring.boot.collections.protoc_generated.CartItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CartItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CartItem)
      com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eric.spring.boot.collections.protoc_generated.CartItemImpl.internal_static_CartItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eric.spring.boot.collections.protoc_generated.CartItemImpl.internal_static_CartItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eric.spring.boot.collections.protoc_generated.CartItem.class, com.eric.spring.boot.collections.protoc_generated.CartItem.Builder.class);
    }

    // Construct using com.eric.spring.boot.collections.protoc_generated.CartItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      quantity_ = 0;

      if (itemBuilder_ == null) {
        item_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.eric.spring.boot.collections.protoc_generated.CartItemImpl.internal_static_CartItem_descriptor;
    }

    @java.lang.Override
    public com.eric.spring.boot.collections.protoc_generated.CartItem getDefaultInstanceForType() {
      return com.eric.spring.boot.collections.protoc_generated.CartItem.getDefaultInstance();
    }

    @java.lang.Override
    public com.eric.spring.boot.collections.protoc_generated.CartItem build() {
      com.eric.spring.boot.collections.protoc_generated.CartItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.eric.spring.boot.collections.protoc_generated.CartItem buildPartial() {
      com.eric.spring.boot.collections.protoc_generated.CartItem result = new com.eric.spring.boot.collections.protoc_generated.CartItem(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.quantity_ = quantity_;
      if (itemBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          item_ = java.util.Collections.unmodifiableList(item_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.item_ = item_;
      } else {
        result.item_ = itemBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.eric.spring.boot.collections.protoc_generated.CartItem) {
        return mergeFrom((com.eric.spring.boot.collections.protoc_generated.CartItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.eric.spring.boot.collections.protoc_generated.CartItem other) {
      if (other == com.eric.spring.boot.collections.protoc_generated.CartItem.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (itemBuilder_ == null) {
        if (!other.item_.isEmpty()) {
          if (item_.isEmpty()) {
            item_ = other.item_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemIsMutable();
            item_.addAll(other.item_);
          }
          onChanged();
        }
      } else {
        if (!other.item_.isEmpty()) {
          if (itemBuilder_.isEmpty()) {
            itemBuilder_.dispose();
            itemBuilder_ = null;
            item_ = other.item_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemFieldBuilder() : null;
          } else {
            itemBuilder_.addAllMessages(other.item_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.eric.spring.boot.collections.protoc_generated.CartItem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.eric.spring.boot.collections.protoc_generated.CartItem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <code>int32 quantity = 21;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <code>int32 quantity = 21;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 quantity = 21;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      
      quantity_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.eric.spring.boot.collections.protoc_generated.Items> item_ =
      java.util.Collections.emptyList();
    private void ensureItemIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        item_ = new java.util.ArrayList<com.eric.spring.boot.collections.protoc_generated.Items>(item_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.eric.spring.boot.collections.protoc_generated.Items, com.eric.spring.boot.collections.protoc_generated.Items.Builder, com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder> itemBuilder_;

    /**
     * <code>repeated .Items item = 3;</code>
     */
    public java.util.List<com.eric.spring.boot.collections.protoc_generated.Items> getItemList() {
      if (itemBuilder_ == null) {
        return java.util.Collections.unmodifiableList(item_);
      } else {
        return itemBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public int getItemCount() {
      if (itemBuilder_ == null) {
        return item_.size();
      } else {
        return itemBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.Items getItem(int index) {
      if (itemBuilder_ == null) {
        return item_.get(index);
      } else {
        return itemBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder setItem(
        int index, com.eric.spring.boot.collections.protoc_generated.Items value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.set(index, value);
        onChanged();
      } else {
        itemBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder setItem(
        int index, com.eric.spring.boot.collections.protoc_generated.Items.Builder builderForValue) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder addItem(com.eric.spring.boot.collections.protoc_generated.Items value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.add(value);
        onChanged();
      } else {
        itemBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder addItem(
        int index, com.eric.spring.boot.collections.protoc_generated.Items value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemIsMutable();
        item_.add(index, value);
        onChanged();
      } else {
        itemBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder addItem(
        com.eric.spring.boot.collections.protoc_generated.Items.Builder builderForValue) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.add(builderForValue.build());
        onChanged();
      } else {
        itemBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder addItem(
        int index, com.eric.spring.boot.collections.protoc_generated.Items.Builder builderForValue) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder addAllItem(
        java.lang.Iterable<? extends com.eric.spring.boot.collections.protoc_generated.Items> values) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, item_);
        onChanged();
      } else {
        itemBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder clearItem() {
      if (itemBuilder_ == null) {
        item_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public Builder removeItem(int index) {
      if (itemBuilder_ == null) {
        ensureItemIsMutable();
        item_.remove(index);
        onChanged();
      } else {
        itemBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.Items.Builder getItemBuilder(
        int index) {
      return getItemFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder getItemOrBuilder(
        int index) {
      if (itemBuilder_ == null) {
        return item_.get(index);  } else {
        return itemBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public java.util.List<? extends com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder> 
         getItemOrBuilderList() {
      if (itemBuilder_ != null) {
        return itemBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(item_);
      }
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.Items.Builder addItemBuilder() {
      return getItemFieldBuilder().addBuilder(
          com.eric.spring.boot.collections.protoc_generated.Items.getDefaultInstance());
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.Items.Builder addItemBuilder(
        int index) {
      return getItemFieldBuilder().addBuilder(
          index, com.eric.spring.boot.collections.protoc_generated.Items.getDefaultInstance());
    }
    /**
     * <code>repeated .Items item = 3;</code>
     */
    public java.util.List<com.eric.spring.boot.collections.protoc_generated.Items.Builder> 
         getItemBuilderList() {
      return getItemFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.eric.spring.boot.collections.protoc_generated.Items, com.eric.spring.boot.collections.protoc_generated.Items.Builder, com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder> 
        getItemFieldBuilder() {
      if (itemBuilder_ == null) {
        itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.eric.spring.boot.collections.protoc_generated.Items, com.eric.spring.boot.collections.protoc_generated.Items.Builder, com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder>(
                item_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        item_ = null;
      }
      return itemBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CartItem)
  }

  // @@protoc_insertion_point(class_scope:CartItem)
  private static final com.eric.spring.boot.collections.protoc_generated.CartItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.eric.spring.boot.collections.protoc_generated.CartItem();
  }

  public static com.eric.spring.boot.collections.protoc_generated.CartItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CartItem>
      PARSER = new com.google.protobuf.AbstractParser<CartItem>() {
    @java.lang.Override
    public CartItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CartItem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CartItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CartItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.eric.spring.boot.collections.protoc_generated.CartItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

