// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Carts.proto

package com.eric.spring.boot.collections.protoc_generated;

/**
 * Protobuf type {@code Carts}
 */
public final class Carts extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Carts)
    CartsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Carts.newBuilder() to construct.
  private Carts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Carts() {
    id_ = "";
    cartItems_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Carts();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Carts(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              cartItems_ = new java.util.ArrayList<com.eric.spring.boot.collections.protoc_generated.CartItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            cartItems_.add(
                input.readMessage(com.eric.spring.boot.collections.protoc_generated.CartItem.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        cartItems_ = java.util.Collections.unmodifiableList(cartItems_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.eric.spring.boot.collections.protoc_generated.CartsProtoImpl.internal_static_Carts_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.eric.spring.boot.collections.protoc_generated.CartsProtoImpl.internal_static_Carts_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.eric.spring.boot.collections.protoc_generated.Carts.class, com.eric.spring.boot.collections.protoc_generated.Carts.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARTITEMS_FIELD_NUMBER = 2;
  private java.util.List<com.eric.spring.boot.collections.protoc_generated.CartItem> cartItems_;
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.eric.spring.boot.collections.protoc_generated.CartItem> getCartItemsList() {
    return cartItems_;
  }
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder> 
      getCartItemsOrBuilderList() {
    return cartItems_;
  }
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  @java.lang.Override
  public int getCartItemsCount() {
    return cartItems_.size();
  }
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  @java.lang.Override
  public com.eric.spring.boot.collections.protoc_generated.CartItem getCartItems(int index) {
    return cartItems_.get(index);
  }
  /**
   * <code>repeated .CartItem cartItems = 2;</code>
   */
  @java.lang.Override
  public com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder getCartItemsOrBuilder(
      int index) {
    return cartItems_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    for (int i = 0; i < cartItems_.size(); i++) {
      output.writeMessage(2, cartItems_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    for (int i = 0; i < cartItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, cartItems_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.eric.spring.boot.collections.protoc_generated.Carts)) {
      return super.equals(obj);
    }
    com.eric.spring.boot.collections.protoc_generated.Carts other = (com.eric.spring.boot.collections.protoc_generated.Carts) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getCartItemsList()
        .equals(other.getCartItemsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (getCartItemsCount() > 0) {
      hash = (37 * hash) + CARTITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getCartItemsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.eric.spring.boot.collections.protoc_generated.Carts parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.eric.spring.boot.collections.protoc_generated.Carts prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Carts}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Carts)
      com.eric.spring.boot.collections.protoc_generated.CartsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eric.spring.boot.collections.protoc_generated.CartsProtoImpl.internal_static_Carts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eric.spring.boot.collections.protoc_generated.CartsProtoImpl.internal_static_Carts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eric.spring.boot.collections.protoc_generated.Carts.class, com.eric.spring.boot.collections.protoc_generated.Carts.Builder.class);
    }

    // Construct using com.eric.spring.boot.collections.protoc_generated.Carts.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCartItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (cartItemsBuilder_ == null) {
        cartItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        cartItemsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.eric.spring.boot.collections.protoc_generated.CartsProtoImpl.internal_static_Carts_descriptor;
    }

    @java.lang.Override
    public com.eric.spring.boot.collections.protoc_generated.Carts getDefaultInstanceForType() {
      return com.eric.spring.boot.collections.protoc_generated.Carts.getDefaultInstance();
    }

    @java.lang.Override
    public com.eric.spring.boot.collections.protoc_generated.Carts build() {
      com.eric.spring.boot.collections.protoc_generated.Carts result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.eric.spring.boot.collections.protoc_generated.Carts buildPartial() {
      com.eric.spring.boot.collections.protoc_generated.Carts result = new com.eric.spring.boot.collections.protoc_generated.Carts(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (cartItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cartItems_ = java.util.Collections.unmodifiableList(cartItems_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cartItems_ = cartItems_;
      } else {
        result.cartItems_ = cartItemsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.eric.spring.boot.collections.protoc_generated.Carts) {
        return mergeFrom((com.eric.spring.boot.collections.protoc_generated.Carts)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.eric.spring.boot.collections.protoc_generated.Carts other) {
      if (other == com.eric.spring.boot.collections.protoc_generated.Carts.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (cartItemsBuilder_ == null) {
        if (!other.cartItems_.isEmpty()) {
          if (cartItems_.isEmpty()) {
            cartItems_ = other.cartItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCartItemsIsMutable();
            cartItems_.addAll(other.cartItems_);
          }
          onChanged();
        }
      } else {
        if (!other.cartItems_.isEmpty()) {
          if (cartItemsBuilder_.isEmpty()) {
            cartItemsBuilder_.dispose();
            cartItemsBuilder_ = null;
            cartItems_ = other.cartItems_;
            bitField0_ = (bitField0_ & ~0x00000001);
            cartItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCartItemsFieldBuilder() : null;
          } else {
            cartItemsBuilder_.addAllMessages(other.cartItems_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.eric.spring.boot.collections.protoc_generated.Carts parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.eric.spring.boot.collections.protoc_generated.Carts) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.eric.spring.boot.collections.protoc_generated.CartItem> cartItems_ =
      java.util.Collections.emptyList();
    private void ensureCartItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cartItems_ = new java.util.ArrayList<com.eric.spring.boot.collections.protoc_generated.CartItem>(cartItems_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.eric.spring.boot.collections.protoc_generated.CartItem, com.eric.spring.boot.collections.protoc_generated.CartItem.Builder, com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder> cartItemsBuilder_;

    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public java.util.List<com.eric.spring.boot.collections.protoc_generated.CartItem> getCartItemsList() {
      if (cartItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cartItems_);
      } else {
        return cartItemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public int getCartItemsCount() {
      if (cartItemsBuilder_ == null) {
        return cartItems_.size();
      } else {
        return cartItemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.CartItem getCartItems(int index) {
      if (cartItemsBuilder_ == null) {
        return cartItems_.get(index);
      } else {
        return cartItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder setCartItems(
        int index, com.eric.spring.boot.collections.protoc_generated.CartItem value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.set(index, value);
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder setCartItems(
        int index, com.eric.spring.boot.collections.protoc_generated.CartItem.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder addCartItems(com.eric.spring.boot.collections.protoc_generated.CartItem value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.add(value);
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder addCartItems(
        int index, com.eric.spring.boot.collections.protoc_generated.CartItem value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCartItemsIsMutable();
        cartItems_.add(index, value);
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder addCartItems(
        com.eric.spring.boot.collections.protoc_generated.CartItem.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.add(builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder addCartItems(
        int index, com.eric.spring.boot.collections.protoc_generated.CartItem.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        cartItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder addAllCartItems(
        java.lang.Iterable<? extends com.eric.spring.boot.collections.protoc_generated.CartItem> values) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cartItems_);
        onChanged();
      } else {
        cartItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder clearCartItems() {
      if (cartItemsBuilder_ == null) {
        cartItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        cartItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public Builder removeCartItems(int index) {
      if (cartItemsBuilder_ == null) {
        ensureCartItemsIsMutable();
        cartItems_.remove(index);
        onChanged();
      } else {
        cartItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.CartItem.Builder getCartItemsBuilder(
        int index) {
      return getCartItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder getCartItemsOrBuilder(
        int index) {
      if (cartItemsBuilder_ == null) {
        return cartItems_.get(index);  } else {
        return cartItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public java.util.List<? extends com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder> 
         getCartItemsOrBuilderList() {
      if (cartItemsBuilder_ != null) {
        return cartItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cartItems_);
      }
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.CartItem.Builder addCartItemsBuilder() {
      return getCartItemsFieldBuilder().addBuilder(
          com.eric.spring.boot.collections.protoc_generated.CartItem.getDefaultInstance());
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public com.eric.spring.boot.collections.protoc_generated.CartItem.Builder addCartItemsBuilder(
        int index) {
      return getCartItemsFieldBuilder().addBuilder(
          index, com.eric.spring.boot.collections.protoc_generated.CartItem.getDefaultInstance());
    }
    /**
     * <code>repeated .CartItem cartItems = 2;</code>
     */
    public java.util.List<com.eric.spring.boot.collections.protoc_generated.CartItem.Builder> 
         getCartItemsBuilderList() {
      return getCartItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.eric.spring.boot.collections.protoc_generated.CartItem, com.eric.spring.boot.collections.protoc_generated.CartItem.Builder, com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder> 
        getCartItemsFieldBuilder() {
      if (cartItemsBuilder_ == null) {
        cartItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.eric.spring.boot.collections.protoc_generated.CartItem, com.eric.spring.boot.collections.protoc_generated.CartItem.Builder, com.eric.spring.boot.collections.protoc_generated.CartItemOrBuilder>(
                cartItems_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cartItems_ = null;
      }
      return cartItemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Carts)
  }

  // @@protoc_insertion_point(class_scope:Carts)
  private static final com.eric.spring.boot.collections.protoc_generated.Carts DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.eric.spring.boot.collections.protoc_generated.Carts();
  }

  public static com.eric.spring.boot.collections.protoc_generated.Carts getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Carts>
      PARSER = new com.google.protobuf.AbstractParser<Carts>() {
    @java.lang.Override
    public Carts parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Carts(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Carts> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Carts> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.eric.spring.boot.collections.protoc_generated.Carts getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

