// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Items.proto

package com.eric.spring.boot.collections.protoc_generated;

public interface ItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Items)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();
}
