// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemsResponse.proto

package com.eric.spring.boot.service.protoc_generated;

public interface AllItemsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AllItemsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Items items = 1;</code>
   */
  java.util.List<com.eric.spring.boot.collections.protoc_generated.Items> 
      getItemsList();
  /**
   * <code>repeated .Items items = 1;</code>
   */
  com.eric.spring.boot.collections.protoc_generated.Items getItems(int index);
  /**
   * <code>repeated .Items items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .Items items = 1;</code>
   */
  java.util.List<? extends com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .Items items = 1;</code>
   */
  com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder getItemsOrBuilder(
      int index);
}
