// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemsResponse.proto

package com.eric.spring.boot.service.protoc_generated;

public interface SingleItemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SingleItemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Items items = 1;</code>
   * @return Whether the items field is set.
   */
  boolean hasItems();
  /**
   * <code>.Items items = 1;</code>
   * @return The items.
   */
  com.eric.spring.boot.collections.protoc_generated.Items getItems();
  /**
   * <code>.Items items = 1;</code>
   */
  com.eric.spring.boot.collections.protoc_generated.ItemsOrBuilder getItemsOrBuilder();
}
