// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ItemsResponse.proto

package com.eric.spring.boot.service.protoc_generated;

public interface SingleItemsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SingleItemsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
